import esCatalog from './locales/es.json';
import frCatalog from './locales/fr.json';
import itCatalog from './locales/it.json';

export const locales = ['pt-BR', 'en', 'es', 'it', 'fr'] as const;
export type Locale = (typeof locales)[number];

export const localeLabels: Record<Locale, string> = {
  'pt-BR': 'Português (Brasil)',
  en: 'English',
  es: 'Español',
  it: 'Italiano',
  fr: 'Français',
};

export function isRtl(_locale: Locale) {
  return false;
}

const ptBR = {
  language: { label: 'Idioma' },
  navigation: { home: 'Início', how: 'Como usar', security: 'Segurança', privacy: 'Privacidade', terms: 'Termos', support: 'Apoie o projeto' },
  meta: { siteTitle: 'axismind', homeTitle: 'Seu espaço para registrar o dia', howTitle: 'Como usar', securityTitle: 'Segurança', privacyTitle: 'Política de Privacidade', termsTitle: 'Termos de Uso', supportTitle: 'Apoie o projeto' },
  home: {
    eyebrow: 'Um diário do seu jeito', title: 'Seu espaço para registrar o dia.', description: 'Reúna experiências, rotina e anotações em um diário pessoal que permanece no seu aparelho.', primaryCta: 'Veja como usar', secondaryCta: 'Conheça a privacidade', disclaimer: 'Para pessoas com 18 anos ou mais. Você escolhe o que registrar, guardar e exportar.', principlesEyebrow: 'Feito para o cotidiano', principlesTitle: 'Organização pessoal com privacidade e escolhas claras.', feature1Title: 'Privado por padrão', feature1Body: 'Seus registros ficam no cofre criptografado do aparelho. Não existe sincronização automática do diário.', feature2Title: 'Texto ou voz', feature2Body: 'Registre no seu ritmo e revise a transcrição antes de guardar qualquer conteúdo.', feature3Title: 'Percepções do dia a dia', feature3Body: 'Humor, sono, rotina e observações corporais podem ser registrados como percepções pessoais, sem interpretações automáticas.', feature4Title: 'Você escolhe quando compartilhar', feature4Body: 'Exporte períodos em PDF ou faça uma cópia segura para guardar onde preferir.', screenshotsEyebrow: 'Prévia do aplicativo', screenshotsTitle: 'Uma experiência simples e acolhedora', screenshotsDescription: 'Quatro capturas provisórias da experiência atual, selecionadas por representarem o diário geral.', transparencyEyebrow: 'Transparência desde o início', transparencyTitle: 'Saiba o que fica no aparelho e o que só sai por sua escolha.', transparencyCta: 'Conhecer os controles',
  },
  how: { eyebrow: 'Guia de uso', title: 'Comece com calma e mantenha você no controle.', intro: 'O axismind organiza registros pessoais no próprio aparelho. Você decide o que faz sentido guardar ou compartilhar.', stepLabel: 'Passo', step1Title: 'Crie seu cofre', step1Body: 'Leia os documentos, confirme que tem 18 anos ou mais e defina uma senha forte. Ela protege o cofre local e não é enviada para nós.', step2Title: 'Registre o dia', step2Body: 'Use texto, voz, humor, sono, rotina ou observações corporais. Tudo funciona como registro cotidiano e percepção pessoal.', step3Title: 'Se preferir, fale', step3Body: 'Baixe o modelo local de transcrição, grave e revise o texto. Só confirme quando ele representar o que você quis dizer.', step4Title: 'Releia no seu ritmo', step4Body: 'As perguntas pessoais ajudam a revisitar o que você escreveu sem criar rótulos ou conclusões sobre você.', step5Title: 'Leve seus registros', step5Body: 'Escolha um período para gerar PDF ou exporte uma cópia segura. Guarde os arquivos com cuidado.', demoEyebrow: 'Capturas provisórias', demoTitle: 'Conheça a experiência atual', demoBody: 'As imagens atuais documentam a interface e serão renovadas em uma etapa posterior.', demoAlt: 'Capturas provisórias da experiência do axismind', helpTitle: 'Conversas sob sua escolha', helpBody: 'A pessoa de confiança e qualquer serviço externo são opções independentes, abertas somente após uma ação e uma confirmação suas.' },
  support: { eyebrow: 'Apoio transparente', title: 'Ajude o axismind a continuar independente.', intro: 'O apoio é voluntário e não altera os recursos disponíveis no aplicativo. Qualquer valor ajuda a manter o projeto.', dataTitle: 'Dados para apoio', beneficiary: 'Beneficiário', pixKeyLabel: 'Chave PIX (e-mail)', qrHint: 'O QR Code não define um valor: escolha quanto deseja apoiar no aplicativo do seu banco.', qrCaption: 'Escaneie para apoiar via PIX', unavailableTitle: 'Informações ainda não cadastradas', unavailableBody: 'Os dados serão publicados somente depois da confirmação do beneficiário e da finalidade.', securityTitle: 'Segurança', securityBody: 'O site nunca solicitará senha bancária, código de autenticação, foto de documento ou dados do cartão. Prefira uma chave PIX aleatória ou institucional em vez de CPF.', doubt: 'Em caso de dúvida, confirme pelo canal oficial:', internationalTitle: 'Apoio internacional', internationalBody: 'Uma opção para contribuições internacionais será adicionada futuramente.' },
  privacy: { title: 'Política de Privacidade', intro: 'Esta política descreve como o aplicativo e este site tratam informações, em linguagem direta.', s1: '1. Controlador e contato', s2: '2. O que é o axismind', s3: '3. Dados e finalidades', s4: '4. Onde ficam os dados', s5: '5. Conexões externas', s6: '6. Direitos e exclusão', s7: '7. Segurança e limites', s8: '8. Idade e mudanças', body1: 'Controlador: {controller}, pessoa física, {location}. Canal para privacidade e direitos: {email}. Política pública: {url}.', body2: 'O axismind é um diário pessoal local-first. Permite registrar texto, voz transcrita, momentos rápidos, observações corporais, lembretes, perguntas pessoais e preparação de conversas.', body3: 'Relatos, registros do dia, reflexões, observações corporais e lembretes são usados para diário, organização pessoal e avisos opcionais. O processamento desses dados acontece localmente. O áudio é usado para transcrição e revisão local, com armazenamento privado temporário. Nome, foto e e-mail formam a identidade opcional do perfil. A pessoa de confiança oferece um atalho manual de contato e nunca é acionada automaticamente. PDF e cópia segura permitem a portabilidade escolhida pela pessoa.', body4: 'O conteúdo do diário fica no cofre criptografado do aparelho enquanto o perfil existir. Não há sincronização automática, publicidade, venda de dados ou treinamento de IA externa com relatos. A exclusão do cofre remove os dados locais conhecidos. Arquivos exportados passam a ficar sob controle da pessoa e do destino escolhido.', body5: 'Conexões externas só ocorrem após ação explícita: Google ou Apple para identidade básica, servidor de distribuição para obter o modelo de transcrição, loja para avaliação e compartilhador do sistema para PDF ou cópia segura. Esses fornecedores podem tratar dados técnicos conforme suas próprias políticas, inclusive em outros países. O conteúdo do diário não é anexado automaticamente a essas conexões.', body6: 'Você pode acessar e corrigir registros no app, exportar uma cópia e excluir integralmente o cofre local. A exclusão também revoga o consentimento local. Solicitações adicionais de confirmação, acesso, correção, eliminação, informação, portabilidade e outros direitos previstos na LGPD podem ser encaminhadas para {email}. Depois de procurar o controlador, também é possível peticionar perante a ANPD.', body7: 'O banco local usa SQLCipher; senha e cópia segura usam derivação de chave e criptografia autenticada. O PDF não possui senha nesta versão. Mantenha o bloqueio de tela e o sistema atualizados. Nenhum controle elimina todos os riscos, especialmente em aparelhos comprometidos ou quando um arquivo é exportado.', body8: 'O aplicativo é destinado exclusivamente a pessoas com {age} anos ou mais e não possui fluxo de consentimento parental. Mudanças relevantes incrementam a versão do documento e exigem novo aceite dentro do app.' },
  terms: { title: 'Termos de Uso', intro: 'Ao usar o axismind, você confirma que compreendeu a natureza pessoal e local da ferramenta e seus limites.', s1: '1. Fornecedor', s2: '2. Elegibilidade', s3: '3. Natureza e limites', s4: '4. Responsabilidades da pessoa usuária', s5: '5. Recursos opcionais', s6: '6. Exportações e perda de acesso', s7: '7. Propriedade e uso adequado', s8: '8. Mudanças', body1: 'O axismind é disponibilizado por {controller}, pessoa física, {location}. Contato: {email}.', body2: 'O produto é destinado exclusivamente a pessoas com {age} anos ou mais. Não existe fluxo de consentimento parental nesta versão.', body3: 'O app auxilia a registrar e organizar experiências pessoais, rotina, lembretes e conversas. As sugestões locais servem apenas para organizar o conteúdo informado pela própria pessoa.', body4: 'Mantenha a senha e o aparelho protegidos. Revise transcrições e relatórios antes de guardar ou compartilhar. Evite dados sensíveis de terceiros sem autorização. Faça uma cópia segura antes de excluir o cofre ou trocar de aparelho.', body5: 'Voz, lembretes, pessoa de confiança, login social, PDF e cópia segura dependem de escolha da pessoa e de permissões do sistema. Fabricantes e sistemas podem limitar alarmes, notificações e execução em segundo plano.', body6: 'Arquivos exportados ficam sob responsabilidade da pessoa. O controlador não recebe uma cópia do cofre e não consegue recuperar a senha local perdida. A exclusão do cofre é irreversível sem uma cópia segura válida.', body7: 'A marca, a interface e o conteúdo autoral são protegidos. É proibido usar o produto para violar direitos, tentar acessar dados de terceiros ou contornar controles de segurança.', body8: 'Alterações relevantes nos Termos serão identificadas por nova versão e novo aceite no aplicativo.' },
  security: { eyebrow: 'Privacidade por arquitetura', title: 'Segurança local, explicada com transparência.', intro: 'O axismind foi desenhado para reduzir a exposição dos relatos: o dado pessoal permanece no aparelho e cada saída depende de uma ação explícita da pessoa.', controlsTitle: 'Controles presentes no aplicativo', control1Title: 'Cofre local criptografado', control1Body: 'O conteúdo pessoal fica no banco SQLCipher do aparelho. A chave do cofre é protegida pelo armazenamento seguro do sistema.', control2Title: 'Sem sincronização automática', control2Body: 'O diário não é enviado para uma nuvem do axismind. Backup e PDF só saem do aparelho quando a própria pessoa escolhe exportar.', control3Title: 'Backup do sistema bloqueado', control3Body: 'As regras do Android impedem que o conteúdo privado do aplicativo entre no backup automático ou na extração comum de dados.', control4Title: 'Build Android analisado', control4Body: 'O APK 1.5.16 de homologação passou por análise estática local com MobSF 4.5.2 e por auditoria do inventário JavaScript em 7 de setembro de 2026.', resultEyebrow: 'Avaliação automatizada independente', resultTitle: 'O que a análise estática encontrou', stat1: 'trackers de privacidade detectados no APK analisado', stat2: 'achados de configuração de segurança de rede', stat3: 'combinações de pacote e versão consultadas sem advisory npm conhecido na data', resultDisclaimer: 'Esta é uma fotografia automatizada do build de homologação, não uma certificação nem garantia de ausência de vulnerabilidades. Alertas foram revisados no contexto do aplicativo e a análise será repetida no artefato assinado para publicação. Testes manuais e atualização contínua das dependências continuam fazendo parte do processo.', tool: 'Ferramenta utilizada:' },
  footer: { description: 'Um diário pessoal local-first para experiências, rotina e anotações.', information: 'Informações', contact: 'Contato', terms: 'Termos de uso', copyright: 'conteúdo informativo' },
  gallery: { enlarge: 'Ampliar', enlargeAria: 'Ampliar imagem: {title}', close: 'Fechar imagem ampliada', dialogAria: 'Imagem ampliada. Use scroll, duplo clique ou dois dedos para zoom; arraste para mover. Pressione Escape para fechar.', item1Title: 'Um diário para o seu dia', item2Title: 'Comece com calma', item3Title: 'Registros cotidianos', item4Title: 'Observação corporal descritiva', item1Alt: 'Tela de introdução do axismind como diário pessoal', item2Alt: 'Tela de boas-vindas para registrar o dia no axismind', item3Alt: 'Tela inicial com opções de registros cotidianos no axismind', item4Alt: 'Tela de observação corporal descritiva no axismind', qrAlt: 'QR Code PIX para a chave {email}' },
  accessibility: { skip: 'Pular para o conteúdo', mainNav: 'Navegação principal', mobileNav: 'Navegação móvel' },
  copy: { idle: 'Copiar chave PIX', copied: 'Chave PIX copiada', error: 'Não foi possível copiar' },
} as const;

type Widen<T> = { -readonly [K in keyof T]: T[K] extends string ? string : T[K] extends object ? Widen<T[K]> : T[K] };
export type Messages = Widen<typeof ptBR>;

const en: Messages = {
  language: { label: 'Language' }, navigation: { home: 'Home', how: 'How it works', security: 'Security', privacy: 'Privacy', terms: 'Terms', support: 'Support the project' }, meta: { siteTitle: 'axismind', homeTitle: 'Your space to record the day', howTitle: 'How it works', securityTitle: 'Security', privacyTitle: 'Privacy Policy', termsTitle: 'Terms of Use', supportTitle: 'Support the project' },
  home: { eyebrow: 'A journal in your own way', title: 'Your space to record the day.', description: 'Bring experiences, routines, and notes together in a personal journal that stays on your device.', primaryCta: 'See how to use it', secondaryCta: 'Explore privacy', disclaimer: 'For people aged 18 and over. You choose what to record, keep, and export.', principlesEyebrow: 'Made for everyday life', principlesTitle: 'Personal organization with privacy and clear choices.', feature1Title: 'Private by default', feature1Body: 'Your entries stay in the device’s encrypted vault. The journal is never automatically synchronized.', feature2Title: 'Text or voice', feature2Body: 'Record at your own pace and review the transcription before saving anything.', feature3Title: 'Everyday perceptions', feature3Body: 'Mood, sleep, routines, and body observations can be recorded as personal perceptions, without automatic interpretations.', feature4Title: 'You choose when to share', feature4Body: 'Export periods as PDF or make a secure copy to keep wherever you prefer.', screenshotsEyebrow: 'App preview', screenshotsTitle: 'A simple, welcoming experience', screenshotsDescription: 'Four provisional screenshots of the current experience, selected to represent the general journal.', transparencyEyebrow: 'Transparency from the start', transparencyTitle: 'Know what stays on the device and what leaves only by your choice.', transparencyCta: 'Explore the controls' },
  how: { eyebrow: 'Usage guide', title: 'Start gently and stay in control.', intro: 'axismind organizes personal entries on the device itself. You decide what makes sense to keep or share.', stepLabel: 'Step', step1Title: 'Create your vault', step1Body: 'Read the documents, confirm you are 18 or older and set a strong password. It protects the local vault and is never sent to us.', step2Title: 'Record the day', step2Body: 'Use text, voice, mood, sleep, routines, or body observations. Everything works as an everyday record and personal perception.', step3Title: 'Speak if you prefer', step3Body: 'Download the local transcription model, record and review the text. Confirm it only when it reflects what you meant.', step4Title: 'Revisit at your pace', step4Body: 'Personal questions help you revisit what you wrote without creating labels or conclusions about you.', step5Title: 'Take your entries with you', step5Body: 'Choose a period to generate a PDF or export a secure copy. Keep files carefully.', demoEyebrow: 'Provisional screenshots', demoTitle: 'Explore the current experience', demoBody: 'The current images document the interface and will be renewed at a later stage.', demoAlt: 'Provisional screenshots of the axismind experience', helpTitle: 'Conversations by your choice', helpBody: 'A trusted person and any external service are independent options, opened only after your action and confirmation.' },
  support: { eyebrow: 'Transparent support', title: 'Help axismind remain independent.', intro: 'Support is voluntary and does not change the features available in the app. Any amount helps keep the project going.', dataTitle: 'Support details', beneficiary: 'Beneficiary', pixKeyLabel: 'PIX key (email)', qrHint: 'The QR Code does not set an amount: choose how much to support in your bank app.', qrCaption: 'Scan to support via PIX', unavailableTitle: 'Information not registered yet', unavailableBody: 'Details will be published only after the beneficiary and purpose are confirmed.', securityTitle: 'Security', securityBody: 'The site will never request a bank password, authentication code, document photo or card details. Prefer a random or institutional PIX key instead of a tax ID.', doubt: 'If in doubt, confirm through the official channel:', internationalTitle: 'International support', internationalBody: 'An option for international contributions will be added in the future.' },
  privacy: { title: 'Privacy Policy', intro: 'This policy describes how the app and this site handle information, in direct language.', s1: '1. Controller and contact', s2: '2. What axismind is', s3: '3. Data and purposes', s4: '4. Where data stays', s5: '5. External connections', s6: '6. Rights and deletion', s7: '7. Security and limits', s8: '8. Age and changes', body1: 'Controller: {controller}, an individual, {location}. Privacy and rights channel: {email}. Public policy: {url}.', body2: 'axismind is a local-first personal journal. It lets you record text, transcribed voice, quick moments, body observations, reminders, personal questions, and conversation preparation.', body3: 'Entries, daily records, reflections, body observations, and reminders are used for journaling, personal organization, and optional alerts. This data is processed locally. Audio is used for local transcription and review, with temporary private storage. Name, photo, and email make up the optional profile identity. The trusted person feature provides a manual contact shortcut and is never triggered automatically. PDF and secure copy features provide portability chosen by the user.', body4: 'Journal content stays in the device’s encrypted vault while the profile exists. There is no automatic synchronization, advertising, data sale, or external AI training with entries. Deleting the vault removes known local data. Exported files become controlled by the person and the chosen destination.', body5: 'External connections only happen after an explicit action: Google or Apple for basic identity, a distribution server to obtain the transcription model, the store for reviews, and the system share sheet for PDF or secure copy. These providers may process technical data under their own policies, including in other countries. Journal content is not automatically attached to these connections.', body6: 'You can access and correct records in the app, export a copy, and fully delete the local vault. Deletion also revokes local consent. Additional requests for confirmation, access, correction, deletion, information, portability, and other rights under Brazil’s LGPD can be sent to {email}. After contacting the controller, a petition may also be filed with Brazil’s ANPD.', body7: 'The local database uses SQLCipher; passwords and secure copies use key derivation and authenticated encryption. PDFs are not password-protected in this version. Keep the screen lock and system updated. No control eliminates every risk, especially on compromised devices or when a file is exported.', body8: 'The app is exclusively for people aged {age} and over and has no parental consent flow. Material changes increment the document version and require new acceptance in the app.' },
  terms: { title: 'Terms of Use', intro: 'By using axismind, you confirm that you understand the personal and local nature of the tool and its limits.', s1: '1. Provider', s2: '2. Eligibility', s3: '3. Nature and limits', s4: '4. User responsibilities', s5: '5. Optional features', s6: '6. Exports and loss of access', s7: '7. Ownership and proper use', s8: '8. Changes', body1: 'axismind is provided by {controller}, an individual, {location}. Contact: {email}.', body2: 'The product is exclusively for people aged {age} and over. This version has no parental consent flow.', body3: 'The app helps record and organize personal experiences, routines, reminders, and conversations. Local suggestions only organize content provided by the user.', body4: 'Keep the password and device protected. Review transcriptions and reports before storing or sharing them. Avoid sensitive third-party data without authorization. Create a secure copy before deleting the vault or changing devices.', body5: 'Voice, reminders, trusted person, social sign-in, PDF, and secure copy depend on the person’s choice and system permissions. Manufacturers and systems may limit alarms, notifications, and background execution.', body6: 'Exported files are the person’s responsibility. The controller receives no copy of the vault and cannot recover a lost local password. Deleting the vault is irreversible without a valid secure copy.', body7: 'The brand, interface, and authored content are protected. The product must not be used to violate rights, try to access third-party data, or bypass security controls.', body8: 'Material changes to the Terms will be identified by a new version and new acceptance in the app.' },
  security: { eyebrow: 'Privacy by architecture', title: 'Local security, explained transparently.', intro: 'axismind was designed to reduce exposure of notes: personal data stays on the device and every exit depends on an explicit action.', controlsTitle: 'Controls present in the app', control1Title: 'Encrypted local vault', control1Body: 'Personal content stays in the device’s SQLCipher database. The vault key is protected by the system secure storage.', control2Title: 'No automatic synchronization', control2Body: 'The journal is not sent to an axismind cloud. Backup and PDF leave the device only when the person chooses to export.', control3Title: 'System backup blocked', control3Body: 'Android rules prevent private app content from entering automatic backup or ordinary data extraction.', control4Title: 'Android build analyzed', control4Body: 'The APK 1.5.16 staging build underwent local static analysis with MobSF 4.5.2 and JavaScript inventory audit on September 7, 2026.', resultEyebrow: 'Independent automated assessment', resultTitle: 'What static analysis found', stat1: 'privacy trackers detected in the analyzed APK', stat2: 'network security configuration findings', stat3: 'package/version combinations checked with no known npm advisory on the date', resultDisclaimer: 'This is an automated snapshot of a staging build, not a certification or guarantee that vulnerabilities are absent. Alerts were reviewed in app context and analysis will be repeated on the signed release artifact. Manual testing and continuous dependency updates remain part of the process.', tool: 'Tool used:' },
  footer: { description: 'A local-first personal journal for experiences, routines, and notes.', information: 'Information', contact: 'Contact', terms: 'Terms of use', copyright: 'informational content' },
  gallery: { enlarge: 'Enlarge', enlargeAria: 'Enlarge image: {title}', close: 'Close enlarged image', dialogAria: 'Enlarged image. Use scroll, double-click or two fingers to zoom; drag to move. Press Escape to close.', item1Title: 'A journal for your day', item2Title: 'Start gently', item3Title: 'Everyday entries', item4Title: 'Descriptive body observation', item1Alt: 'Introduction screen presenting axismind as a personal journal', item2Alt: 'Welcome screen for recording the day in axismind', item3Alt: 'Home screen with everyday entry options in axismind', item4Alt: 'Descriptive body observation screen in axismind', qrAlt: 'PIX QR Code for key {email}' }, accessibility: { skip: 'Skip to content', mainNav: 'Main navigation', mobileNav: 'Mobile navigation' }, copy: { idle: 'Copy PIX key', copied: 'PIX key copied', error: 'Could not copy' },
};

const catalogs: Record<Locale, Messages> = {
  'pt-BR': ptBR as unknown as Messages,
  en,
  es: esCatalog,
  it: itCatalog,
  fr: frCatalog,
};

export const messages: Record<Locale, Messages> = catalogs;

export function interpolate(value: string, variables: Record<string, string | number> = {}) {
  return value.replace(/\{(\w+)\}/g, (_, key: string) => String(variables[key] ?? `{${key}}`));
}
