import arCatalog from './locales/ar.json';
import deCatalog from './locales/de.json';
import esCatalog from './locales/es.json';
import frCatalog from './locales/fr.json';
import heCatalog from './locales/he.json';
import itCatalog from './locales/it.json';
import jaCatalog from './locales/ja.json';
import koCatalog from './locales/ko.json';
import ruCatalog from './locales/ru.json';
import zhCNCatalog from './locales/zh-CN.json';

export const locales = ['pt-BR', 'en', 'es', 'it', 'fr', 'ru', 'de', 'zh-CN', 'ja', 'ko', 'ar', 'he'] as const;
export type Locale = (typeof locales)[number];

export const localeLabels: Record<Locale, string> = {
  'pt-BR': 'Português (Brasil)',
  en: 'English',
  es: 'Español',
  it: 'Italiano',
  fr: 'Français',
  ru: 'Русский',
  de: 'Deutsch',
  'zh-CN': '简体中文',
  ja: '日本語',
  ko: '한국어',
  ar: 'العربية',
  he: 'עברית',
};

export function isRtl(locale: Locale) {
  return locale === 'ar' || locale === 'he';
}

const ptBR = {
  language: { label: 'Idioma' },
  navigation: { home: 'Início', how: 'Como usar', security: 'Segurança', privacy: 'Privacidade', terms: 'Termos', support: 'Apoie o projeto' },
  meta: { siteTitle: 'axismind', homeTitle: 'Um espaço privado para organizar o que você sente', howTitle: 'Como usar', securityTitle: 'Segurança', privacyTitle: 'Política de Privacidade', termsTitle: 'Termos de Uso', supportTitle: 'Apoie o projeto' },
  home: {
    eyebrow: 'Cuidado pessoal, no seu ritmo', title: 'Um espaço privado para organizar o que você sente', description: 'Diário local de bem-estar emocional, com relatos, check-ins, lembretes e preparação para conversas de cuidado.', primaryCta: 'Entenda como funciona', secondaryCta: 'Como protegemos seus dados', disclaimer: 'Para maiores de 18 anos. O axismind não diagnostica, prescreve ou substitui profissionais e serviços de emergência.', principlesEyebrow: 'Princípios do produto', principlesTitle: 'Uma ferramenta de organização pessoal, não uma avaliação clínica.', feature1Title: 'Privado por padrão', feature1Body: 'Seus relatos ficam no cofre criptografado do aparelho. Não existe sincronização automática do diário.', feature2Title: 'Texto ou voz', feature2Body: 'Registre no seu ritmo e revise a transcrição antes de guardar qualquer conteúdo.', feature3Title: 'Feito para o cotidiano', feature3Body: 'Check-ins, humor rápido, consciência corporal e lembretes opcionais em uma jornada acolhedora.', feature4Title: 'Você escolhe quando compartilhar', feature4Body: 'Exporte períodos em PDF ou faça uma cópia criptografada para guardar onde preferir.', screenshotsEyebrow: 'Prévia do aplicativo', screenshotsTitle: 'Conheça a experiência', screenshotsDescription: 'Capturas reais do candidato Android 1.5.17, build 26, executado no perfil de demonstração Thais Vieira.', transparencyEyebrow: 'Transparência desde o início', transparencyTitle: 'Saiba o que fica no aparelho e o que só sai por sua escolha.', transparencyCta: 'Conhecer os controles',
  },
  how: { eyebrow: 'Guia de uso', title: 'Comece com calma e mantenha você no controle.', intro: 'O axismind organiza registros pessoais no próprio aparelho. Nenhuma etapa exige que você conclua o que sente ou compartilhe um relato.', stepLabel: 'Passo', step1Title: 'Crie seu cofre', step1Body: 'Leia os documentos, confirme que tem 18 anos ou mais e defina uma senha forte. Ela protege o cofre local e não é enviada para nós.', step2Title: 'Registre o momento', step2Body: 'Use texto, humor rápido, check-in ou consciência corporal. Você escolhe quais informações deseja guardar.', step3Title: 'Se preferir, fale', step3Body: 'Baixe o modelo local de transcrição, grave e revise o texto. Só confirme quando ele representar o que você quis dizer.', step4Title: 'Revise sem rótulos', step4Body: 'As perguntas de reflexão são abertas e conservadoras. Elas não definem diagnóstico, emoção ou tratamento.', step5Title: 'Leve seu histórico', step5Body: 'Escolha um período para gerar PDF ou exporte o cofre criptografado. Guarde os arquivos com cuidado.', demoEyebrow: 'Demonstração visual', demoTitle: 'Veja como é simples usar o aplicativo', demoBody: 'A animação mostra uma jornada real no aplicativo: consentimento, criação do cofre, perfil com foto, relato, reflexão, voz e relatório. Ela foi apenas acelerada e não contém instruções sobrepostas à interface.', demoAlt: 'Demonstração animada dos cinco passos para usar o axismind', helpTitle: 'Se você precisar de ajuda imediata', helpBody: 'O aplicativo oferece atalhos acionados por você, mas não monitora crises nem chama socorro automaticamente. No Brasil, o CVV atende pelo 188. Em emergência médica, procure o serviço de emergência local.' },
  support: { eyebrow: 'Apoio transparente', title: 'Ajude o axismind a continuar cuidadoso e independente.', intro: 'O apoio é voluntário, não oferece recursos extras no aplicativo e não condiciona atendimento. Qualquer valor ajuda a manter o projeto.', dataTitle: 'Dados para apoio', beneficiary: 'Beneficiário', pixKeyLabel: 'Chave PIX (e-mail)', qrHint: 'O QR Code não define um valor: escolha quanto deseja apoiar no aplicativo do seu banco.', qrCaption: 'Escaneie para apoiar via PIX', unavailableTitle: 'Informações ainda não cadastradas', unavailableBody: 'Os dados serão publicados somente depois da confirmação do beneficiário e da finalidade.', securityTitle: 'Segurança', securityBody: 'O site nunca solicitará senha bancária, código de autenticação, foto de documento ou dados do cartão. Prefira uma chave PIX aleatória ou institucional em vez de CPF.', doubt: 'Em caso de dúvida, confirme pelo canal oficial:', internationalTitle: 'Apoio internacional', internationalBody: 'Uma opção para contribuições internacionais será adicionada futuramente.' },
  privacy: { title: 'Política de Privacidade', intro: 'Esta política descreve como o aplicativo e este site tratam informações, em linguagem direta.', s1: '1. Controlador e contato', s2: '2. O que é o axismind', s3: '3. Dados e finalidades', s4: '4. Onde ficam os dados', s5: '5. Conexões externas', s6: '6. Direitos e exclusão', s7: '7. Segurança e limites', s8: '8. Idade e mudanças', body1: 'Controlador: {controller}, pessoa física, {location}. Canal para privacidade e direitos: {email}.', body2: 'É um diário pessoal de bem-estar emocional local-first. Permite registrar texto, voz transcrita, check-ins, sensações corporais, medicação informada e preparação para consultas. Não diagnostica, prescreve ou trata condições de saúde e não substitui profissionais nem serviços de emergência.', body3: 'Relatos, check-ins, reflexões, corpo e medicação informada: diário, autorreflexão e lembretes opcionais. Áudio: transcrição e revisão local, com armazenamento privado temporário. Nome, foto e e-mail: identidade opcional do perfil. Contato de confiança: acesso rápido manual, nunca acionado automaticamente. Recibo legal: registro local da versão aceita. PDF e backup: portabilidade escolhida pela pessoa.', body4: 'O conteúdo do diário fica no cofre criptografado do aparelho. Não há sincronização automática, publicidade, venda de dados ou treinamento de IA externa com relatos. Arquivos exportados passam a ficar sob controle da pessoa e do destino escolhido.', body5: 'Conexões externas só ocorrem após ação explícita: Google ou Apple para identidade básica, servidor de distribuição para obter o modelo de transcrição, loja para avaliação e compartilhador do sistema para PDF ou backup. Este site estático não possui formulário, analytics próprio ou cookies de publicidade; a hospedagem pode manter registros técnicos conforme os termos do provedor.', body6: 'A pessoa pode acessar e corrigir registros no app, exportar uma cópia e excluir integralmente o cofre local. Solicitações adicionais podem ser encaminhadas ao canal informado acima. Depois de tentar exercer o direito junto ao controlador, também é possível peticionar perante a ANPD.', body7: 'O banco local usa SQLCipher; senha e backup utilizam derivação de chave e criptografia autenticada. O PDF não possui senha nesta versão. Nenhum controle elimina todos os riscos, especialmente em aparelhos comprometidos ou quando um arquivo é exportado.', body8: 'O aplicativo é destinado a maiores de {age} anos. Mudanças relevantes incrementam a versão do documento e exigem novo aceite dentro do app.' },
  terms: { title: 'Termos de Uso', intro: 'Ao usar o axismind, você confirma que compreendeu a natureza pessoal e local da ferramenta e seus limites.', s1: '1. Fornecedor', s2: '2. Elegibilidade', s3: '3. Natureza e limites', s4: '4. Responsabilidades da pessoa usuária', s5: '5. Recursos opcionais', s6: '6. Exportações e perda de acesso', s7: '7. Propriedade e uso adequado', s8: '8. Mudanças', body1: 'O axismind é disponibilizado por {controller}, pessoa física, {location}. Contato: {email}.', body2: 'O produto é destinado exclusivamente a pessoas com {age} anos ou mais. Não existe fluxo de consentimento parental nesta versão.', body3: 'O app auxilia a registrar e organizar experiências pessoais. Não realiza diagnóstico, prescrição, tratamento, monitoramento clínico ou acionamento automático de emergência.', body4: 'Manter a senha e o aparelho protegidos. Revisar transcrições e relatórios antes de guardar ou compartilhar. Evitar dados sensíveis de terceiros sem autorização. Fazer backup antes de excluir o cofre ou trocar de aparelho.', body5: 'Voz, lembretes, contato de confiança, login social, PDF e backup dependem de escolha e permissões do sistema. Fabricantes e sistemas podem limitar alarmes, notificações e execução em segundo plano.', body6: 'Arquivos exportados ficam sob responsabilidade da pessoa. O controlador não recebe uma cópia do cofre e não consegue recuperar a senha local perdida. A exclusão do cofre é irreversível sem backup válido.', body7: 'A marca, interface e conteúdo autoral são protegidos. É proibido usar o produto para violar direitos, tentar acessar dados de terceiros ou contornar controles de segurança.', body8: 'Alterações relevantes nos Termos serão identificadas por nova versão e novo aceite no aplicativo.' },
  security: { eyebrow: 'Privacidade por arquitetura', title: 'Segurança local, explicada com transparência.', intro: 'O axismind foi desenhado para reduzir a exposição dos relatos: o dado pessoal permanece no aparelho e cada saída depende de uma ação explícita da pessoa.', controlsTitle: 'Controles presentes no aplicativo', control1Title: 'Cofre local criptografado', control1Body: 'O conteúdo pessoal fica no banco SQLCipher do aparelho. A chave do cofre é protegida pelo armazenamento seguro do sistema.', control2Title: 'Sem sincronização automática', control2Body: 'O diário não é enviado para uma nuvem do axismind. Backup e PDF só saem do aparelho quando a própria pessoa escolhe exportar.', control3Title: 'Backup do sistema bloqueado', control3Body: 'As regras do Android impedem que o conteúdo privado do aplicativo entre no backup automático ou na extração comum de dados.', control4Title: 'Build Android analisado', control4Body: 'O APK 1.5.16 de homologação passou por análise estática local com MobSF 4.5.2 e por auditoria do inventário JavaScript em 7 de setembro de 2026.', resultEyebrow: 'Avaliação automatizada independente', resultTitle: 'O que a análise estática encontrou', stat1: 'trackers de privacidade detectados no APK analisado', stat2: 'achados de configuração de segurança de rede', stat3: 'combinações de pacote e versão consultadas sem advisory npm conhecido na data', resultDisclaimer: 'Esta é uma fotografia automatizada do build de homologação, não uma certificação nem garantia de ausência de vulnerabilidades. Alertas foram revisados no contexto do aplicativo e a análise será repetida no artefato assinado para publicação. Testes manuais e atualização contínua das dependências continuam fazendo parte do processo.', tool: 'Ferramenta utilizada:' },
  footer: { description: 'Um diário pessoal local-first. Não oferece diagnóstico, prescrição, tratamento ou atendimento de emergência.', information: 'Informações', contact: 'Contato', terms: 'Termos de uso', copyright: 'conteúdo informativo' },
  gallery: { enlarge: 'Ampliar', enlargeAria: 'Ampliar imagem: {title}', close: 'Fechar imagem ampliada', dialogAria: 'Imagem ampliada. Use scroll, duplo clique ou dois dedos para zoom; arraste para mover. Pressione Escape para fechar.', item1Title: 'Jornada principal', item2Title: 'Cuidado e consulta', item3Title: 'Entendimento sem diagnóstico', item4Title: 'Exportação sob controle da pessoa', item1Alt: 'Captura real da jornada principal do axismind', item2Alt: 'Mosaico com oito capturas reais de recursos de cuidado e preparação para consulta do axismind', item3Alt: 'Mosaico com oito capturas reais de recursos de entendimento sem diagnóstico do axismind', item4Alt: 'Mosaico com oito capturas reais de exportação, privacidade e recuperação do axismind', qrAlt: 'QR Code PIX para a chave {email}' },
  accessibility: { skip: 'Pular para o conteúdo', mainNav: 'Navegação principal', mobileNav: 'Navegação móvel' },
  copy: { idle: 'Copiar chave PIX', copied: 'Chave PIX copiada', error: 'Não foi possível copiar' },
} as const;

type Widen<T> = { -readonly [K in keyof T]: T[K] extends string ? string : T[K] extends object ? Widen<T[K]> : T[K] };
export type Messages = Widen<typeof ptBR>;

const en: Messages = {
  language: { label: 'Language' }, navigation: { home: 'Home', how: 'How it works', security: 'Security', privacy: 'Privacy', terms: 'Terms', support: 'Support the project' }, meta: { siteTitle: 'axismind', homeTitle: 'A private space to organize what you feel', howTitle: 'How it works', securityTitle: 'Security', privacyTitle: 'Privacy Policy', termsTitle: 'Terms of Use', supportTitle: 'Support the project' },
  home: { eyebrow: 'Personal care, at your pace', title: 'A private space to organize what you feel', description: 'A local emotional wellbeing journal with notes, check-ins, reminders and preparation for care conversations.', primaryCta: 'See how it works', secondaryCta: 'How we protect your data', disclaimer: 'For people aged 18 and over. axismind does not diagnose, prescribe or replace professionals and emergency services.', principlesEyebrow: 'Product principles', principlesTitle: 'A personal organization tool, not a clinical assessment.', feature1Title: 'Private by default', feature1Body: 'Your notes stay in the device’s encrypted vault. The journal is never automatically synchronized.', feature2Title: 'Text or voice', feature2Body: 'Record at your own pace and review the transcription before saving anything.', feature3Title: 'Made for everyday life', feature3Body: 'Check-ins, quick mood tracking, body awareness and optional reminders in a welcoming journey.', feature4Title: 'You choose when to share', feature4Body: 'Export periods as PDF or make an encrypted copy to keep wherever you prefer.', screenshotsEyebrow: 'App preview', screenshotsTitle: 'Explore the experience', screenshotsDescription: 'Real captures from Android candidate 1.5.17, build 26, run with the Thais Vieira demo profile.', transparencyEyebrow: 'Transparency from the start', transparencyTitle: 'Know what stays on the device and what leaves only by your choice.', transparencyCta: 'Explore the controls' },
  how: { eyebrow: 'Usage guide', title: 'Start gently and stay in control.', intro: 'axismind organizes personal records on the device itself. No step asks you to conclude what you feel or share a note.', stepLabel: 'Step', step1Title: 'Create your vault', step1Body: 'Read the documents, confirm you are 18 or older and set a strong password. It protects the local vault and is never sent to us.', step2Title: 'Record the moment', step2Body: 'Use text, quick mood, check-in or body awareness. You choose what to keep.', step3Title: 'Speak if you prefer', step3Body: 'Download the local transcription model, record and review the text. Confirm it only when it reflects what you meant.', step4Title: 'Review without labels', step4Body: 'Reflection questions are open and conservative. They do not define diagnosis, emotion or treatment.', step5Title: 'Take your history with you', step5Body: 'Choose a period to generate a PDF or export the encrypted vault. Keep files carefully.', demoEyebrow: 'Visual demo', demoTitle: 'See how simple the app is to use', demoBody: 'The animation shows a real app journey: consent, vault creation, profile photo, note, reflection, voice and report. It is only sped up and contains no instructions over the interface.', demoAlt: 'Animated demonstration of the five steps to use axismind', helpTitle: 'If you need immediate help', helpBody: 'The app offers shortcuts you trigger yourself, but it does not monitor crises or call for help automatically. In Brazil, CVV is available at 188. In a medical emergency, contact your local emergency service.' },
  support: { eyebrow: 'Transparent support', title: 'Help axismind remain careful and independent.', intro: 'Support is voluntary, provides no extra in-app features and does not condition care. Any amount helps keep the project going.', dataTitle: 'Support details', beneficiary: 'Beneficiary', pixKeyLabel: 'PIX key (email)', qrHint: 'The QR Code does not set an amount: choose how much to support in your bank app.', qrCaption: 'Scan to support via PIX', unavailableTitle: 'Information not registered yet', unavailableBody: 'Details will be published only after the beneficiary and purpose are confirmed.', securityTitle: 'Security', securityBody: 'The site will never request a bank password, authentication code, document photo or card details. Prefer a random or institutional PIX key instead of a tax ID.', doubt: 'If in doubt, confirm through the official channel:', internationalTitle: 'International support', internationalBody: 'An option for international contributions will be added in the future.' },
  privacy: { title: 'Privacy Policy', intro: 'This policy describes how the app and this site handle information, in direct language.', s1: '1. Controller and contact', s2: '2. What axismind is', s3: '3. Data and purposes', s4: '4. Where data stays', s5: '5. External connections', s6: '6. Rights and deletion', s7: '7. Security and limits', s8: '8. Age and changes', body1: 'Controller: {controller}, an individual, {location}. Privacy and rights channel: {email}.', body2: 'A local-first personal emotional wellbeing journal. It records text, transcribed voice, check-ins, body sensations, reported medication and preparation for appointments. It does not diagnose, prescribe or treat health conditions and does not replace professionals or emergency services.', body3: 'Notes, check-ins, reflections, body and reported medication: journaling, self-reflection and optional reminders. Audio: local transcription and review with temporary private storage. Name, photo and email: optional profile identity. Trusted contact: manual quick access, never triggered automatically. Legal receipt: local record of the accepted version. PDF and backup: portability chosen by the person.', body4: 'Journal content stays in the device’s encrypted vault. There is no automatic synchronization, advertising, data sale or external AI training with notes. Exported files are controlled by the person and the chosen destination.', body5: 'External connections happen only after an explicit action: Google or Apple for basic identity, a distribution server for the transcription model, the store for reviews and the system share sheet for PDF or backup. This static site has no form, own analytics or advertising cookies; hosting may keep technical logs under the provider terms.', body6: 'People can access and correct records in the app, export a copy and fully delete the local vault. Additional requests can be sent to the channel above. After contacting the controller, a petition may also be filed with ANPD.', body7: 'The local database uses SQLCipher; password and backup use key derivation and authenticated encryption. PDFs are not password-protected in this version. No control removes every risk, especially on compromised devices or when a file is exported.', body8: 'The app is for people aged {age} and over. Material changes increment the document version and require new acceptance in the app.' },
  terms: { title: 'Terms of Use', intro: 'By using axismind, you confirm that you understand the personal and local nature of the tool and its limits.', s1: '1. Provider', s2: '2. Eligibility', s3: '3. Nature and limits', s4: '4. User responsibilities', s5: '5. Optional features', s6: '6. Exports and loss of access', s7: '7. Ownership and proper use', s8: '8. Changes', body1: 'axismind is provided by {controller}, an individual, {location}. Contact: {email}.', body2: 'The product is exclusively for people aged {age} and over. This version has no parental consent flow.', body3: 'The app helps record and organize personal experiences. It does not diagnose, prescribe, treat, clinically monitor or automatically call emergency services.', body4: 'Keep the password and device protected. Review transcriptions and reports before storing or sharing. Avoid sensitive third-party data without authorization. Back up before deleting the vault or changing devices.', body5: 'Voice, reminders, trusted contact, social login, PDF and backup depend on user choice and system permissions. Manufacturers and systems may limit alarms, notifications and background execution.', body6: 'Exported files are the person’s responsibility. The controller receives no vault copy and cannot recover a lost local password. Deleting the vault is irreversible without a valid backup.', body7: 'The brand, interface and authored content are protected. It is forbidden to use the product to violate rights, access third-party data or bypass security controls.', body8: 'Material changes to the Terms will be identified by a new version and new acceptance in the app.' },
  security: { eyebrow: 'Privacy by architecture', title: 'Local security, explained transparently.', intro: 'axismind was designed to reduce exposure of notes: personal data stays on the device and every exit depends on an explicit action.', controlsTitle: 'Controls present in the app', control1Title: 'Encrypted local vault', control1Body: 'Personal content stays in the device’s SQLCipher database. The vault key is protected by the system secure storage.', control2Title: 'No automatic synchronization', control2Body: 'The journal is not sent to an axismind cloud. Backup and PDF leave the device only when the person chooses to export.', control3Title: 'System backup blocked', control3Body: 'Android rules prevent private app content from entering automatic backup or ordinary data extraction.', control4Title: 'Android build analyzed', control4Body: 'The APK 1.5.16 staging build underwent local static analysis with MobSF 4.5.2 and JavaScript inventory audit on September 7, 2026.', resultEyebrow: 'Independent automated assessment', resultTitle: 'What static analysis found', stat1: 'privacy trackers detected in the analyzed APK', stat2: 'network security configuration findings', stat3: 'package/version combinations checked with no known npm advisory on the date', resultDisclaimer: 'This is an automated snapshot of a staging build, not a certification or guarantee that vulnerabilities are absent. Alerts were reviewed in app context and analysis will be repeated on the signed release artifact. Manual testing and continuous dependency updates remain part of the process.', tool: 'Tool used:' },
  footer: { description: 'A local-first personal journal. It does not provide diagnosis, prescription, treatment or emergency care.', information: 'Information', contact: 'Contact', terms: 'Terms of use', copyright: 'informational content' },
  gallery: { enlarge: 'Enlarge', enlargeAria: 'Enlarge image: {title}', close: 'Close enlarged image', dialogAria: 'Enlarged image. Use scroll, double-click or two fingers to zoom; drag to move. Press Escape to close.', item1Title: 'Main journey', item2Title: 'Care and consultation', item3Title: 'Understanding without diagnosis', item4Title: 'Export under your control', item1Alt: 'Real screenshot from the axismind main journey', item2Alt: 'Mosaic with eight real screenshots of care and consultation preparation features', item3Alt: 'Mosaic with eight real screenshots of understanding without diagnosis features', item4Alt: 'Mosaic with eight real screenshots of export, privacy and recovery features', qrAlt: 'PIX QR Code for key {email}' }, accessibility: { skip: 'Skip to content', mainNav: 'Main navigation', mobileNav: 'Mobile navigation' }, copy: { idle: 'Copy PIX key', copied: 'PIX key copied', error: 'Could not copy' },
};

const catalogs: Record<Locale, Messages> = {
  'pt-BR': ptBR as unknown as Messages,
  en,
  es: esCatalog,
  it: itCatalog,
  fr: frCatalog,
  ru: ruCatalog,
  de: deCatalog,
  'zh-CN': zhCNCatalog,
  ja: jaCatalog,
  ko: koCatalog,
  ar: arCatalog,
  he: heCatalog,
};

export const messages: Record<Locale, Messages> = catalogs;

export function interpolate(value: string, variables: Record<string, string | number> = {}) {
  return value.replace(/\{(\w+)\}/g, (_, key: string) => String(variables[key] ?? `{${key}}`));
}
